# -*- coding: utf-8 -*-
"""REGAL_DNN_training_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kpd3PaxyuI5zB3kg95L8hq17lPeCCjwh
"""

# -*- coding: utf-8 -*-
#!/usr/bin/env python3

import os
import re
import argparse
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, Subset, WeightedRandomSampler
from torchvision import models
from torchvision.models import EfficientNet_B0_Weights
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import StratifiedGroupKFold
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

def set_seed(seed: int = 50): #to reproduce
    torch.manual_seed(seed)
    np.random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

#get params from filename
def parse_distance_from_filename(filepath):
    basename = os.path.basename(filepath)
    match = re.search(r"_d([\d.]+)_", basename)
    if match:
        return float(match.group(1))
    match = re.search(r"([\d.]+)Mpc", basename, re.IGNORECASE)
    if match:
        return float(match.group(1))
    raise ValueError(
        f"Could not find distance from filename: {basename}\n"
        "Expected '_d<distance>_' or '<distance>Mpc' in the filename."
    )


def parse_ellipticity_from_filename(filepath):
    basename = os.path.basename(filepath)
    match = re.search(r"_e([\d.]+)", basename)
    return float(match.group(1)) if match else None


def galaxy_group(filepath):
    """Strip augmentation/rotation/residual/cropped suffixes -> base galaxy name."""
    basename = os.path.basename(filepath)
    basename = re.sub(r"\.(fits|npz)$", "", basename)
    return re.sub(r"_aug\d+_rot\d+(_residual)?(_cropped)?$", "", basename)

#to have stability; replace batch norm with group norm
def replace_bn_with_gn(module, num_groups=8):
    for name, child in module.named_children():
        if isinstance(child, nn.BatchNorm2d):
            num_channels = child.num_features
            g = num_groups
            while num_channels % g != 0:
                g -= 1
            setattr(module, name, nn.GroupNorm(g, num_channels))
        else:
            replace_bn_with_gn(child, num_groups)

def distance_bins(log_distances, n_bins=10):
    bins = np.linspace(log_distances.min(), log_distances.max(), n_bins + 1)
    return np.digitize(log_distances, bins, right=True)

#actually we comment this out usually but can be done in future work
def random_crop_fraction(image, fraction):
    h, w = image.shape
    new_h = max(1, int(h * fraction))
    new_w = max(1, int(w * fraction))
    top  = np.random.randint(0, h - new_h + 1)
    left = np.random.randint(0, w - new_w + 1)
    return image[top:top + new_h, left:left + new_w]


def normalise(image: np.ndarray) -> np.ndarray:
    finite = image[np.isfinite(image) & (image != 0)]
    if len(finite) == 0:
        return image
    lo, hi = np.percentile(finite, 0.5), np.percentile(finite, 99.5)
    if hi > lo:
        image = np.clip(image, lo, hi)
        image = (image - lo) / (hi - lo)
    return image

#datast
class SBFDataset(Dataset):
    def __init__(self, npz_path: str, crop_min: float = 0.70, crop_max: float = 0.90):
        print(f"Loading .npz cache: {npz_path}")
        cache = np.load(npz_path, allow_pickle=True)

        all_images  = cache["images"]
        all_log_distances = cache["log_distances"]
        all_paths = list(cache["paths"])

        all_dists_mpc = 10 ** all_log_distances
        valid_mask = all_dists_mpc > 40.0
        n_total  = len(all_paths)
        n_removed  = int((~valid_mask).sum())
        valid_idx  = np.where(valid_mask)[0]

        self.images   = all_images[valid_idx]
        self.log_distances = all_log_distances[valid_idx]
        self.paths  = [all_paths[i] for i in valid_idx]
        self.crop_min   = crop_min
        self.crop_max = crop_max
        self.groups  = np.array([galaxy_group(p) for p in self.paths])

        dists = 10 ** self.log_distances
        print(f"  Loaded {n_total} images; removed {n_removed} with d <= 40 Mpc; "
              f"kept {len(self.paths)}")
        print(f"  Distance range : {dists.min():.1f} - {dists.max():.1f} Mpc")
        print(f"  log10(d) range : {self.log_distances.min():.3f} - "
              f"{self.log_distances.max():.3f}")
        print(f"  Unique galaxies: {len(set(self.groups))}  |  "
              f"Total images: {len(self.paths)}")

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx, augment: bool = False):
        image = self.images[idx].astype(np.float32)
        image = normalise(image)
        tensor = torch.from_numpy(image).unsqueeze(0).repeat(3, 1, 1)
        label = torch.tensor(self.log_distances[idx], dtype=torch.float32)
        return tensor, label

class AugSubset(Dataset):
    def __init__(self, subset: Subset, augment: bool):
        self.subset  = subset
        self.augment = augment

    def __len__(self):
        return len(self.subset)

    def __getitem__(self, idx):
        real_idx = self.subset.indices[idx]
        return self.subset.dataset.__getitem__(real_idx, augment=self.augment)

#allow batch size = 1
def collate_single(batch):
    tensor, label = batch[0]
    return tensor.unsqueeze(0), label.unsqueeze(0)

def make_loader(dataset, indices, args, device, training: bool):
    aug_subset = AugSubset(Subset(dataset, indices), augment=training)

    if training:
        dists_mpc = 10 ** dataset.log_distances[indices]
        bin_edges = [40, 60, 90, 120, np.inf]
        bin_idx  = np.digitize(dists_mpc, bin_edges) - 1
        bin_counts = np.bincount(bin_idx, minlength=len(bin_edges) - 1)
        bin_counts = np.maximum(bin_counts, 1)
        sample_weights = 1.0 / bin_counts[bin_idx]
        #random weighted sampler to prevent impact of class imbalance
        sampler = WeightedRandomSampler(
            weights = torch.DoubleTensor(sample_weights),
            num_samples = len(indices),
            replacement = True,
        )
        return DataLoader(
            aug_subset,
            batch_size  = 1,
            sampler = sampler,
            num_workers = args.num_workers,
            pin_memory = (device.type == "cuda"),
            collate_fn = collate_single,
        )
    else:
        return DataLoader(
            aug_subset,
            batch_size  = 1,
            shuffle = False,
            num_workers = args.num_workers,
            pin_memory = (device.type == "cuda"),
            collate_fn  = collate_single,
        )

#model
class SBFEfficientNetB0(nn.Module):
    def __init__(self, pretrained: bool = True, dropout: float = 0.3):
        super().__init__()
        weights  = EfficientNet_B0_Weights.IMAGENET1K_V1 if pretrained else None
        backbone = models.efficientnet_b0(weights=weights)
        in_features = backbone.classifier[1].in_features
        backbone.classifier = nn.Sequential( #here we change classification to regression head
            nn.Dropout(p=dropout),
            nn.Linear(in_features, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(p=dropout / 2),
            nn.Linear(256, 1),
        )
        replace_bn_with_gn(backbone)
        self.backbone = backbone

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.backbone(x).squeeze(1)

#discriminative fine-tuning
def build_optimizer(model, base_lr, lr_early=0.01, lr_mid=0.1):
    f = model.backbone.features
    early_params = (list(f[0].parameters()) + list(f[1].parameters()) +
                    list(f[2].parameters()) + list(f[3].parameters()))
    mid_params = (list(f[4].parameters()) + list(f[5].parameters()) +
                    list(f[6].parameters()))
    head_params = (list(f[7].parameters()) + list(f[8].parameters()) +
                    list(model.backbone.classifier.parameters()))
    return torch.optim.Adam([
        {"params": early_params, "lr": base_lr * lr_early},
        {"params": mid_params, "lr": base_lr * lr_mid},
        {"params": head_params,  "lr": base_lr * 1.0},
    ])

#training and eval loops
def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss, total_count = 0.0, 0
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        preds = model(images)
        loss = criterion(preds, labels)
        loss.backward()
        optimizer.step()
        total_loss  += loss.item() * len(labels)
        total_count += len(labels)
    return total_loss / total_count


@torch.no_grad()
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss, total_count = 0.0, 0
    all_preds, all_labels   = [], []
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        preds = model(images)
        total_loss  += criterion(preds, labels).item() * len(labels)
        total_count += len(labels)
        all_preds.append(preds.cpu())
        all_labels.append(labels.cpu())
    return total_loss / total_count, torch.cat(all_preds), torch.cat(all_labels)

#evaluation mtrics
def compute_metrics(preds, labels):
    p, l = preds.numpy(), labels.numpy()
    mae  = mean_absolute_error(l, p)
    rmse  = float(np.sqrt(np.mean((p - l) ** 2)))
    r2 = r2_score(l, p)
    med_err_mpc  = float(np.median(np.abs(10**p - 10**l)))
    mean_err_mpc = float(np.mean(np.abs(10**p - 10**l)))
    frac_err = np.abs(10**p - 10**l) / (10**l)
    within_5pct  = float((frac_err <= 0.05).mean())
    within_10pct = float((frac_err <= 0.10).mean())
    res = {
        "MAE_log": mae, "RMSE_log": rmse, "R2": r2,
        "MedianErr_Mpc": med_err_mpc, "MeanErr_Mpc": mean_err_mpc,
        "within_5pct": within_5pct, "within_10pct": within_10pct,
    }
    dist_true = 10 ** l
    for mask, band in [
        (dist_true < 60.0,   "<60 Mpc"),
        (dist_true >= 60.0,  ">=60 Mpc"),
        (dist_true < 100.0,  "<100 Mpc"),
        (dist_true >= 100.0, ">=100 Mpc"),
    ]:
        if mask.sum() < 2:
            continue
        p_s, l_s = p[mask], l[mask]
        res[f"MAE_log_{band}"]  = mean_absolute_error(l_s, p_s)
        res[f"RMSE_log_{band}"]  = float(np.sqrt(np.mean((p_s - l_s) ** 2)))
        res[f"R2_{band}"]  = r2_score(l_s, p_s)
        res[f"MedianErr_Mpc_{band}"] = float(np.median(np.abs(10**p_s - 10**l_s)))
        res[f"MeanErr_Mpc_{band}"]   = float(np.mean(np.abs(10**p_s - 10**l_s)))
        frac_s = np.abs(10**p_s - 10**l_s) / (10**l_s)
        res[f"within_5pct_{band}"] = float((frac_s <= 0.05).mean())
        res[f"within_10pct_{band}"]  = float((frac_s <= 0.10).mean())
        res[f"N_{band}"] = int(mask.sum())
    return res


def print_metrics(metrics, prefix=""):
    print(f"{prefix} MAE   = {metrics['MAE_log']:.4f} dex")
    print(f"{prefix} RMSE = {metrics['RMSE_log']:.4f} dex")
    print(f"{prefix} R2 = {metrics['R2']:.4f}")
    print(f"{prefix} MedianErr = {metrics['MedianErr_Mpc']:.2f} Mpc")
    print(f"{prefix} MeanErr   = {metrics['MeanErr_Mpc']:.2f} Mpc")
    print(f"{prefix} within 5% = {metrics['within_5pct']*100:.1f}%  |  "
          f"within 10% = {metrics['within_10pct']*100:.1f}%")
    for band in ["<60 Mpc", ">=60 Mpc", "<100 Mpc", ">=100 Mpc"]:
        if f"R2_{band}" in metrics:
            n = metrics.get(f"N_{band}", "?")
            print(
                f"{prefix}  [{band}  n={n}]  "
                f"MAE={metrics[f'MAE_log_{band}']:.4f} dex  "
                f"R2={metrics[f'R2_{band}']:.4f}  "
                f"MedianErr={metrics[f'MedianErr_Mpc_{band}']:.2f} Mpc  "
                f"MeanErr={metrics[f'MeanErr_Mpc_{band}']:.2f} Mpc  "
                f"within5%={metrics.get(f'within_5pct_{band}', float('nan'))*100:.1f}%  "
                f"within10%={metrics.get(f'within_10pct_{band}', float('nan'))*100:.1f}%"
            )


#ALL PLOT
#tried to be consistent w font sizes everywhere
TITLE_FS = 22
LABEL_FS = 20
TICK_FS  = 18
LEGEND_FS = 16
ANNOT_FS  = 15


def plot_distance_histograms(dataset, train_idx, val_idx, output_dir, fold=1):
    bin_edges   = [40, 60, 90, 120, 150]
    bin_labels  = ["40-60", "60-90", "90-120", "120-150"]
    bin_centres = [50, 75, 105, 135]

    def counts(indices):
        d = 10 ** dataset.log_distances[indices]
        return [int(((d >= bin_edges[i]) & (d < bin_edges[i + 1])).sum())
                for i in range(len(bin_edges) - 1)]

    all_idx = np.arange(len(dataset))
    c_full = counts(all_idx)
    c_train = counts(train_idx)
    c_val  = counts(val_idx)

    fig, axes = plt.subplots(1, 3, figsize=(16, 5), sharey=False)
    palette  = ["#4C72B0", "#DD8452", "#55A868"]
    panels = [
        (c_full, "Full dataset (post-filter)"),
        (c_train, f"Training fold {fold}"),
        (c_val, f"Validation fold {fold}"),
    ]
    for ax, (c, title), colour in zip(axes, panels, palette):
        bars = ax.bar(bin_centres, c, width=24, color=colour, alpha=0.85,
                      edgecolor="white")
        ax.set_xticks(bin_centres)
        ax.set_xticklabels(bin_labels, fontsize=TICK_FS)
        ax.set_xlabel("Distance (Mpc)", fontsize=LABEL_FS)
        ax.set_ylabel("Number of images", fontsize=LABEL_FS)
        ax.set_title(title, fontsize=TITLE_FS, fontweight="bold")
        ax.tick_params(labelsize=TICK_FS)
        ax.grid(True, axis="y", alpha=0.4, linestyle="--")
        for bar, n in zip(bars, c):
            ax.text(bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + max(c) * 0.01,
                    str(n), ha="center", va="bottom", fontsize=ANNOT_FS)
    plt.tight_layout()
    fpath = os.path.join(output_dir, f"distance_histograms_fold{fold}.png")
    plt.savefig(fpath, dpi=150)
    plt.close()
    print(f"Saved distance histograms: {fpath}")


def plot_predictions(preds, labels, epoch, output_dir, tag="val"):
    p, l = preds.numpy(), labels.numpy()
    fig, ax = plt.subplots(figsize=(7, 7))
    sc = ax.scatter(l, p, s=6, alpha=0.4, color="blue")
    lims = [min(l.min(), p.min()), max(l.max(), p.max())]
    ax.plot(lims, lims, "r--", lw=1.5, label="1:1")
    ax.set_xlabel(r"True $\log_{10}(d/\mathrm{Mpc})$", fontsize=LABEL_FS)
    ax.set_ylabel(r"Predicted $\log_{10}(d/\mathrm{Mpc})$", fontsize=LABEL_FS)
    ax.set_title(f"Epoch {epoch:03d}  [{tag}]", fontsize=TITLE_FS, fontweight="bold")
    ax.tick_params(labelsize=TICK_FS)
    ax.legend(fontsize=LEGEND_FS)
    ax.grid(True, alpha=0.4, linestyle="--")
    plt.tight_layout()
    plt.savefig(
        os.path.join(output_dir, f"pred_vs_true_{tag}_epoch{epoch:03d}.png"), dpi=150
    )
    plt.close()


def plot_loss_curve(train_losses, val_losses, output_dir, fold=None):
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(train_losses, label="train", lw=2)
    ax.plot(val_losses,   label="val",   lw=2)
    ax.set_xlabel("Epoch", fontsize=LABEL_FS)
    ax.set_ylabel(r"Huber loss $[\log_{10}\,\mathrm{Mpc}]$", fontsize=LABEL_FS)
    title = "Training / Validation Loss"
    fname = "loss_curve.png"
    if fold is not None:
        title += f" (fold {fold})"
        fname  = f"loss_curve_fold{fold}.png"
    ax.set_title(title, fontsize=TITLE_FS, fontweight="bold")
    ax.tick_params(labelsize=TICK_FS)
    ax.legend(fontsize=LEGEND_FS)
    ax.grid(True, alpha=0.4, linestyle="--")
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, fname), dpi=150)
    plt.close()

def plot_residuals(preds, labels, output_dir, tag="test"):
    p, l      = 10 ** preds.numpy(), 10 ** labels.numpy()
    residuals = p - l
    fig, ax   = plt.subplots(figsize=(9, 5))
    ax.scatter(l, residuals, s=6, alpha=0.4, color="coral")
    ax.axhline(0, color="k",  lw=1.5, ls="--")
    ax.axvline(60, color="royalblue", lw=1.5, ls=":", label="60 Mpc")
    ax.axvline(100, color="grey",  lw=1.5, ls=":", label="100 Mpc")
    ax.set_xlabel("True distance (Mpc)", fontsize=LABEL_FS)
    ax.set_ylabel("Predicted - True (Mpc)", fontsize=LABEL_FS)
    ax.set_title(f"Residuals [{tag}]", fontsize=TITLE_FS, fontweight="bold")
    ax.tick_params(labelsize=TICK_FS)
    ax.legend(fontsize=LEGEND_FS)
    ax.grid(True, alpha=0.4, linestyle="--")
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, f"residuals_{tag}.png"), dpi=150)
    plt.close()

#grad-cam heat maps
class GradCAM:
    def __init__(self, model: nn.Module, target_layer: nn.Module):
        self.model = model
        self.activations = None
        self.gradients   = None
        self._fwd = target_layer.register_forward_hook(self._save_act)
        self._bwd = target_layer.register_full_backward_hook(self._save_grad)

    def _save_act(self, m, i, o):    self.activations = o.detach()
    def _save_grad(self, m, gi, go): self.gradients   = go[0].detach()

    def __call__(self, inp: torch.Tensor) -> np.ndarray:
        self.model.eval()
        inp = inp.requires_grad_(True)
        out = self.model(inp)
        self.model.zero_grad()
        out.sum().backward()
        weights = self.gradients.mean(dim=(2, 3), keepdim=True)
        cam = (weights * self.activations).sum(dim=1).squeeze()
        cam = torch.clamp(cam, min=0)
        vmin, vmax = cam.min(), cam.max()
        if vmax > vmin:
            cam = (cam - vmin) / (vmax - vmin)
        return cam.cpu().numpy()

    def remove(self):
        self._fwd.remove()
        self._bwd.remove()


#optional plot; i didn't really use this anywhere
def plot_calibration(all_fold_preds_list, test_labels, output_dir, tag="test_ensemble"):
    preds_stack = torch.stack(all_fold_preds_list, dim=0)
    mean_pred   = preds_stack.mean(dim=0).numpy()
    std_pred = preds_stack.std(dim=0).numpy()

    true_mpc = 10**test_labels.numpy()
    pred_mpc = 10**mean_pred
    err_mpc = 10**(mean_pred + std_pred) - pred_mpc

    order = np.argsort(true_mpc)
    t_sorted = true_mpc[order]
    p_sorted = pred_mpc[order]
    e_sorted = err_mpc[order]

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    ax = axes[0]
    step = max(1, len(t_sorted) // 300)
    ax.errorbar(
        t_sorted[::step], p_sorted[::step],
        yerr=e_sorted[::step],
        fmt="o", ms=3, alpha=0.5, color="steelblue",
        ecolor="lightsteelblue", elinewidth=0.8, capsize=0,
        label="Ensemble mean ± fold std"
    )
    lims = [min(t_sorted.min(), p_sorted.min()) * 0.95,
            max(t_sorted.max(), p_sorted.max()) * 1.05]
    ax.plot(lims, lims, "r--", lw=1.5, label="1:1")
    ax.set_xlabel("True distance (Mpc)", fontsize=LABEL_FS)
    ax.set_ylabel("Predicted distance (Mpc)", fontsize=LABEL_FS)
    ax.set_title("Calibration: predicted vs true\n(error bars = fold ensemble spread)",
                 fontsize=TITLE_FS, fontweight="bold")
    ax.tick_params(labelsize=TICK_FS)
    ax.legend(fontsize=LEGEND_FS)
    ax.grid(True, alpha=0.4, linestyle="--")

    ax = axes[1]
    sc = ax.scatter(true_mpc, err_mpc, s=6, alpha=0.4,
                    c=true_mpc, cmap="viridis")
    cbar = plt.colorbar(sc, ax=ax)
    cbar.set_label("True distance (Mpc)", fontsize=ANNOT_FS)
    cbar.ax.tick_params(labelsize=ANNOT_FS)
    ax.set_xlabel("True distance (Mpc)", fontsize=LABEL_FS)
    ax.set_ylabel("Fold spread σ (Mpc)", fontsize=LABEL_FS)
    ax.set_title("Ensemble uncertainty vs distance\n(higher = less consistent across folds)",
                 fontsize=TITLE_FS, fontweight="bold")
    ax.tick_params(labelsize=TICK_FS)
    ax.grid(True, alpha=0.4, linestyle="--")

    plt.tight_layout()
    out = os.path.join(output_dir, f"calibration_{tag}.png")
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved calibration plot: {out}")

def select_gradcam_samples(dataset, bin_width_mpc=25):
    dists = 10 ** dataset.log_distances
    d_min = int(dists.min())
    d_max = int(dists.max()) + 1
    bins = range(d_min, d_max, bin_width_mpc)
    selected = []
    rng = np.random.default_rng(42)

    for b_lo in bins:
        b_hi = b_lo + bin_width_mpc
        in_bin = np.where((dists >= b_lo) & (dists < b_hi))[0]
        if len(in_bin) == 0:
            continue
        for compare in [
            lambda e: e is not None and e >= 0.4,
            lambda e: e is not None and e <= 0.1,
        ]:
            candidates = [
                i for i in in_bin
                if compare(parse_ellipticity_from_filename(dataset.paths[i]))
            ]
            if candidates:
                selected.append(int(rng.choice(candidates)))

    seen, unique = set(), []
    for i in selected:
        if i not in seen:
            seen.add(i)
            unique.append(i)
    print(f"Grad-CAM: selected {len(unique)} images across distance range")
    return unique

#gradcam run for all layers
def run_gradcam(model, dataset, sample_indices, output_dir, device, fold):
    gcam_dir = os.path.join(output_dir, "gradcam")
    os.makedirs(gcam_dir, exist_ok=True)

    f = model.backbone.features
    layers = {
        "block0_stem": f[0],
        "block1_mbconv1": f[1],
        "block2_mbconv2": f[2],
        "block3_mbconv3": f[3],
        "block4_mbconv4": f[4],
        "block5_mbconv5": f[5],
        "block6_mbconv6": f[6],
        "block7_mbconv7": f[7],
        "block8_head": f[8],
    }

    for layer_name, layer in layers.items():
        gcam = GradCAM(model, layer)
        n    = len(sample_indices)

        cols = 2
        rows = int(np.ceil(n / cols))
        fig, axes = plt.subplots(rows, cols,
                                 figsize=(cols * 6, rows * 6))
        axes = np.array(axes).flatten()

        for plot_idx, img_idx in enumerate(sample_indices):
            try:
                img_np = dataset.images[img_idx].astype(np.float32)
                tensor = torch.from_numpy(img_np).unsqueeze(0).repeat(3, 1, 1)
                inp = tensor.unsqueeze(0).to(device)

                cam = gcam(inp)
                cam_up = torch.nn.functional.interpolate(
                    torch.tensor(cam).unsqueeze(0).unsqueeze(0),
                    size=img_np.shape,
                    mode="bilinear", align_corners=False,
                ).squeeze().numpy()

                img_disp = (img_np - img_np.min()) / max(
                    img_np.max() - img_np.min(), 1e-8
                )
                with torch.no_grad():
                    pred_log = model(inp).item()
                pred_mpc = 10 ** pred_log
                true_mpc = 10 ** dataset.log_distances[img_idx]
                ellip = parse_ellipticity_from_filename(dataset.paths[img_idx])

                ax = axes[plot_idx]
                ax.imshow(img_disp, cmap="gray", origin="lower")
                im = ax.imshow(cam_up, cmap="jet", alpha=0.45,
                               origin="lower", vmin=0, vmax=1)
                cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
                cbar.set_label("CAM activation", fontsize=ANNOT_FS)
                cbar.ax.tick_params(labelsize=ANNOT_FS)

                ax.set_title(
                    f"true={true_mpc:.0f}  pred={pred_mpc:.0f} Mpc\n"
                    f"e={ellip}  {img_np.shape[0]}x{img_np.shape[1]} px",
                    fontsize=LABEL_FS,
                )
                ax.tick_params(left=False, bottom=False,
                               labelleft=False, labelbottom=False)
            except Exception as e:
                print(f"[GradCAM WARNING] idx={img_idx}: {e}")
                axes[plot_idx].axis("off")

        for ax in axes[n:]:
            ax.axis("off")

        plt.suptitle(
            f"Grad-CAM — fold {fold} — {layer_name}",
            fontsize=TITLE_FS + 2, fontweight="bold"
        )
        plt.tight_layout()
        out_path = os.path.join(gcam_dir, f"gradcam_fold{fold}_{layer_name}.png")
        plt.savefig(out_path, dpi=150, bbox_inches="tight")
        plt.close()
        gcam.remove()
        print(f"  Saved Grad-CAM: {out_path}")


#training loop 1 fold
def train_fold(fold, train_idx, val_idx, dataset, args, device, fold_dir):
    os.makedirs(fold_dir, exist_ok=True)
    print(f"\n{'='*60}")
    print(f"FOLD {fold}  train={len(train_idx)}  val={len(val_idx)}")
    print(f"{'='*60}")

    train_loader = make_loader(dataset, train_idx, args, device, training=True)
    val_loader = make_loader(dataset, val_idx,   args, device, training=False)

    model  = SBFEfficientNetB0(pretrained=True, dropout=args.dropout).to(device)
    criterion = nn.HuberLoss(delta=args.huber_delta)
    optimizer = build_optimizer(model, args.lr, args.lr_early, args.lr_mid)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=1e-6
    )

    best_combined_score = float("inf")
    patience_count = 0
    train_losses, val_losses = [], []

    for epoch in range(1, args.epochs + 1):
        train_loss                      = train_one_epoch(model, train_loader, optimizer, criterion, device)
        val_loss, val_preds, val_labels = evaluate(model, val_loader, criterion, device)
        scheduler.step()

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        metrics  = compute_metrics(val_preds, val_labels)
        combined_score = val_loss + metrics["MAE_log"]

        print(
            f"--Fold {fold} | Epoch {epoch:03d}/{args.epochs} | "
            f"train={train_loss:.6f}  val={val_loss:.6f} | "
            f"MAE={metrics['MAE_log']:.4f} dex  R2={metrics['R2']:.4f}  "
            f"MedianErr={metrics['MedianErr_Mpc']:.2f} Mpc"
        )

        if combined_score < best_combined_score:
            best_combined_score = combined_score
            patience_count = 0
            ckpt_path = os.path.join(fold_dir, "best_model.pt")
            torch.save({
                "fold":  fold,
                "epoch":  epoch,
                "model_state_dict":  model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "val_loss":  val_loss,
                "combined_score":  combined_score,
                "metrics": metrics,
                "hyperparams": {
                    "huber_delta": args.huber_delta,
                    "lr": args.lr,
                    "lr_early": args.lr_early,
                    "lr_mid": args.lr_mid,
                    "dropout": args.dropout,
                    "crop_min": args.crop_min,
                    "crop_max": args.crop_max,
                },
            }, ckpt_path)
            print(
                f"[SAVED] Best checkpoint  "
                f"val={val_loss:.4f}  MAE={metrics['MAE_log']:.4f}  "
                f"score={combined_score:.4f}"
            )
        else:
            patience_count += 1
            #commented out patience
            # if patience_count >= args.patience:
            #     print(f"Early stopping at epoch {epoch}.")
            #     break

        if epoch % args.plot_every == 0 or epoch == args.epochs:
            plot_predictions(val_preds, val_labels, epoch, fold_dir,
                             tag=f"val_fold{fold}")

    plot_loss_curve(train_losses, val_losses, fold_dir, fold=fold)

    print(f"Generating train 1:1 plot for fold {fold} ...")
    ckpt = torch.load(os.path.join(fold_dir, "best_model.pt"), map_location=device)
    model.load_state_dict(ckpt["model_state_dict"])
    train_eval_loader = make_loader(dataset, train_idx, args, device, training=False)
    _, train_preds, train_labels = evaluate(model, train_eval_loader, criterion, device)
    plot_predictions(train_preds, train_labels, ckpt["epoch"], fold_dir,
                     tag=f"train_fold{fold}")
    print(f"  Train metrics (best ckpt):")
    print_metrics(compute_metrics(train_preds, train_labels), prefix="    ")

    if fold == 1:
        print(f"  Running Grad-CAM for fold {fold} ...")
        sample_indices = select_gradcam_samples(dataset,
                                                bin_width_mpc=args.gradcam_bin_mpc)
        run_gradcam(model, dataset, sample_indices, fold_dir, device, fold)

    return fold_dir

#main (what actually runs)
def main(args):
    set_seed(50)
    os.makedirs(args.output_dir, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device : {device}")
    if device.type == "cuda":
        print(f"GPU    : {torch.cuda.get_device_name(0)}")

    if not os.path.isfile(args.npz_cache):
        raise FileNotFoundError(f"Cache file not found: {args.npz_cache}")

    dataset = SBFDataset(
        args.npz_cache,
        crop_min=args.crop_min,
        crop_max=args.crop_max,
    )

    all_idx = np.arange(len(dataset))
    bin_labels = distance_bins(dataset.log_distances)
    groups = dataset.groups

    N_SPLITS = 10
    sgkf  = StratifiedGroupKFold(n_splits=N_SPLITS, shuffle=True, random_state=50)
    folds = list(sgkf.split(all_idx, bin_labels, groups=groups))

    _, test_idx = folds[0]
    print(
        f"\nTest set: fold 0  ->  {len(test_idx)} images "
        f"({len(set(groups[test_idx]))} unique galaxies)"
    )
    test_loader = make_loader(dataset, test_idx, args, device, training=False)

    fold_results = []
    for cv_fold in range(1, min(args.max_cv_folds + 1, N_SPLITS)):
        _, val_idx  = folds[cv_fold]
        train_idx   = np.concatenate([
            fold_idx
            for fi, (_, fold_idx) in enumerate(folds)
            if fi != 0 and fi != cv_fold
        ])

        print(
            f"\nCV fold {cv_fold}: "
            f"train={len(train_idx)} imgs ({len(set(groups[train_idx]))} galaxies)  |  "
            f"val={len(val_idx)} imgs ({len(set(groups[val_idx]))} galaxies)"
        )

        if cv_fold == 1:
            plot_distance_histograms(dataset, train_idx, val_idx,
                                     args.output_dir, fold=cv_fold)

        fold_dir = os.path.join(args.output_dir, f"fold_{cv_fold}")
        train_fold(cv_fold, train_idx, val_idx, dataset, args, device, fold_dir)

        ckpt = torch.load(os.path.join(fold_dir, "best_model.pt"),
                               map_location=device)
        model = SBFEfficientNetB0(pretrained=False, dropout=args.dropout).to(device)
        model.load_state_dict(ckpt["model_state_dict"])
        criterion = nn.HuberLoss(delta=args.huber_delta)

        val_loader = make_loader(dataset, val_idx, args, device, training=False)
        _, val_preds, val_labels = evaluate(model, val_loader, criterion, device)
        metrics = compute_metrics(val_preds, val_labels)
        fold_results.append(metrics)

        print(f"\nFold {cv_fold} best-checkpoint validation metrics:")
        print_metrics(metrics, prefix=f"  fold {cv_fold}")

    print("\n" + "=" * 60)
    print("--cross validation summary-- (folds trained, groups separated)")
    print("=" * 60)
    for key in ["MAE_log", "RMSE_log", "R2", "MedianErr_Mpc", "MeanErr_Mpc", "within_5pct", "within_10pct"]:
        vals = [r[key] for r in fold_results if key in r]
        if vals:
            print(f"  {key:20s}  mean={np.mean(vals):.4f}  std={np.std(vals):.4f}")
    for band in ["<60 Mpc", ">=60 Mpc", "<100 Mpc", ">=100 Mpc"]:
        print(f"\n  [{band}]")
        for key in ["MAE_log", "R2", "MedianErr_Mpc", "MeanErr_Mpc", "within_5pct", "within_10pct"]:
            fkey = f"{key}_{band}"
            vals = [r[fkey] for r in fold_results if fkey in r]
            if vals:
                print(f"  {key:20s}  mean={np.mean(vals):.4f}  std={np.std(vals):.4f}")

    print("\n" + "=" * 60)
    print("--final test results-- (mean ensemble of all trained fold models)")
    print("=" * 60)

    criterion  = nn.HuberLoss(delta=args.huber_delta)
    all_fold_preds = []

    for cv_fold in range(1, min(args.max_cv_folds + 1, N_SPLITS)):
        ckpt_path  = os.path.join(args.output_dir, f"fold_{cv_fold}", "best_model.pt")
        ckpt = torch.load(ckpt_path, map_location=device)
        fold_model = SBFEfficientNetB0(pretrained=False, dropout=args.dropout).to(device)
        fold_model.load_state_dict(ckpt["model_state_dict"])
        _, fold_preds, test_labels = evaluate(fold_model, test_loader, criterion, device)
        all_fold_preds.append(fold_preds)
        print(f"Fold {cv_fold} loaded  "
              f"(epoch {ckpt['epoch']},  val_loss={ckpt['val_loss']:.4f})")

    ensemble_preds = torch.stack(all_fold_preds, dim=0).mean(dim=0)
    ensemble_loss = float(
        nn.HuberLoss(delta=args.huber_delta)(ensemble_preds, test_labels).item()
    )
    ensemble_metrics = compute_metrics(ensemble_preds, test_labels)

    # save for post-hoc diagnostics
    np.save(os.path.join(args.output_dir, "ensemble_preds.npy"), ensemble_preds.numpy())
    np.save(os.path.join(args.output_dir, "test_labels.npy"),   test_labels.numpy())
    np.save(os.path.join(args.output_dir, "test_indices.npy"),  test_idx)

    print(f"\n  Huber loss (ensemble): {ensemble_loss:.4f}")
    print_metrics(ensemble_metrics, prefix="  ")

    ref_epoch = torch.load(
        os.path.join(args.output_dir, "fold_1", "best_model.pt"), map_location="cpu"
    )["epoch"]
    plot_predictions(ensemble_preds, test_labels, ref_epoch,
                     args.output_dir, tag="test_ensemble")
    plot_residuals(ensemble_preds, test_labels, args.output_dir, tag="test_ensemble")
    plot_calibration(all_fold_preds, test_labels, args.output_dir, tag="test_ensemble")
    print("\nAll outputs saved to:", args.output_dir)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="EfficientNet-B0 on pre-cropped residual images — trial 8"
    )

    parser.add_argument("--npz_cache", type=str, required=True)
    parser.add_argument("--output_dir", type=str, default="./checkpoints_trial8")
    parser.add_argument("--epochs", type=int, default=40)
    parser.add_argument("--num_workers", type=int, default=1)
    parser.add_argument("--plot_every", type=int, default=10)
    parser.add_argument("--patience", type=int, default=10)
    parser.add_argument("--min_delta", type=float, default=1e-3)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--lr_early", type=float, default=0.01)
    parser.add_argument("--lr_mid", type=float, default=0.1)
    parser.add_argument("--dropout", type=float, default=0.3)
    parser.add_argument("--huber_delta", type=float, default=0.1)
    parser.add_argument("--crop_min", type=float, default=0.85)
    parser.add_argument("--crop_max", type=float, default=0.95)
    parser.add_argument("--max_cv_folds", type=int, default=5)
    parser.add_argument("--gradcam_bin_mpc", type=int, default=25)

    args = parser.parse_args()
    assert 0.0 < args.crop_min < args.crop_max <= 1.0, \
        "crop_min must be in (0, crop_max] and crop_max <= 1.0"
    main(args)